using Challenge.Api.Config;
using Challenge.Api.Controllers;
using Challenge.Infra.Client;
using Challenge.Infra.CrossCutting.Hubs;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
// Learn more about configuring OpenAPI at https://aka.ms/aspnet/openapi
builder.Services.AddControllers();

builder.Services.AddOpenApi();

var config = new ConfigurationBuilder()
.SetBasePath(Directory.GetCurrentDirectory())
    //.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
    .AddJsonFile($"appsettings.{builder.Environment.EnvironmentName}.json", optional: true, reloadOnChange: true)
    .AddEnvironmentVariables()
    .Build();

var apiUrl = builder.Configuration["ApiUrl"] ?? throw new Exception("ApiUrl is not set");

builder.Services.AddHttpClient<HackNewsClient>(client => client.BaseAddress = new Uri(apiUrl));

IWebHostEnvironment webHostEnvironment = builder.Environment;

NativeInjectorBootStrapper.RegisterServices(builder.Services, config, webHostEnvironment);

var app = builder.Build();

app.UseResponseCompression();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
    app.UseSwaggerUI(options =>
    {
        // Specify the endpoint for the generated OpenAPI JSON file
        // The file generated by MapOpenApi() is typically at /openapi/v1.json
        options.SwaggerEndpoint("/openapi/v1.json", "My API V1");

        // Optional: set the Swagger UI as the application's root page
        // options.RoutePrefix = string.Empty; 
    });
}

//app.UseStatusCodePages(async statusCodeContext
//    => await Results.Problem(statusCode: statusCodeContext.HttpContext.Response.StatusCode)
//                 .ExecuteAsync(statusCodeContext.HttpContext));

NewsMap.ExposeMaps(app);

app.UseCors("CorsPolicy");
app.MapHub<BrokerHub>("/hubs/brokerhub");
app.MapControllers();
app.Run();